</$objtype/mkfile

CC=pcc
OBJ=utils/buffer.$O utils/stack.$O utils/vector.$O \
	utils/errors.$O \
	input/filter.$O input/inputstream.$O \
	charset/aliases.$O  \
	charset/encodings/utf8.$O charset/encodings/utf16.$O \
	charset/codec.$O \
	charset/codecs/codec_8859.$O \
	charset/codecs/codec_ascii.$O charset/codecs/codec_ext8.$O \
	charset/codecs/codec_utf16.$O charset/codecs/codec_utf8.$O \
#	extra/bsearch.$O extra/assert.$O

HFILES=../include/parserutils/parserutils.h

CFLAGS=-I ../include -I . -I ../../posix/include -DWITHOUT_ICONV_FILTER -D_SUSV2_SOURCE

all:V:	libparserutils.$O.a

libparserutils.$O.a: $OBJ $HFILES
	ar rv libparserutils.$O.a $OBJ


%.$O:	%.c $HFILES
	$CC $CFLAGS -c -o $target $stem.c

clean:V:
	rm -f $OBJ libparserutils.$O.a
