</$objtype/mkfile


LIB=libparserutils.$O.a
OBJ=\
	utils/buffer.$O\
	 utils/stack.$O \
	utils/vector.$O \
	utils/errors.$O \
	input/filter.$O input/inputstream.$O \
	charset/aliases.$O  \
	charset/encodings/utf8.$O charset/encodings/utf16.$O \
	charset/codec.$O \
	charset/codecs/codec_8859.$O \
	charset/codecs/codec_ascii.$O charset/codecs/codec_ext8.$O \
	charset/codecs/codec_utf16.$O charset/codecs/codec_utf8.$O \
#	extra/bsearch.$O extra/assert.$O

HFILES=../include/parserutils/parserutils.h charset/aliases.inc

<../../nsport.mk
<../../nsportlib.mk

charset/aliases.inc:
	cp ../../genfiles/libparserutils/aliases.inc charset/aliases.inc
